# Site settings
name: HelloKenLee
email: ken_4000@qq.com
# site info
author: KenLee
url: https://www.hellokenlee.github.io
resume_site: /resume/
github: https://github.com/hellokenlee/
baseurl: 
description: Abstractness is the price of genarality.
meta_description: meta_des
motto: HelloKenLee
banner: 很高兴能在这遇见你!
categories: 1
permalink: /:year/:month/:day/:title/
paginate: 10
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: hellokenlee

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Comment system
FB:
  comments :
    provider : disqus
    disqus :
        short_name : hellokenlee
